### ISSUE TITLE
Door turning invisible

### ISSUE THREAD

**Issue by uniwars** [dev7355608/limits#1]
Hi, it seems that limits will turn door invisible when next to the door but not just in front of it like on my screens :

![image](https://github.com/dev7355608/limits/assets/65986545/f3ca118e-f4c6-4c84-8c66-61eb8a2adbd0)
![image](https://github.com/dev7355608/limits/assets/65986545/540a0c55-491b-4651-812a-148cd2904e61)
![image](https://github.com/dev7355608/limits/assets/65986545/14aff252-693e-4de9-8fe9-286962bc233a)

tested with find the cutprit

Foundry stable v11 305
Pathfinder 2 5.2.1
Limits 0.1.0

**Comment by dev7355608** [comment]
Thanks for the report! Fixed.

https://github.com/dev7355608/limits/releases/tag/v1.0.0
