### ISSUE TITLE
[Feature Request] Option to turn off outline and fill

### ISSUE THREAD

**Issue by txm3278** [dev7355608/limits#10]
I do not believe this is currently possible in core Foundry. Removing the outline and fill would be good for things like darkness where a player should not know how big the darkness is.

**Comment by dev7355608** [comment]
Not really Limits territory. Not sure if there's a module out there, which would be a good fit. Perhaps a new small module is needed that can make the following things happen:
- Invisible templates
- Only grid highlights (on hover).
- Restrict templates to vision / don't render in fog.
