### ISSUE TITLE
Issue with Levels module?

### ISSUE THREAD

**Issue by Zendarino** [dev7355608/limits#12]
I don't know if it's a bug, but when I create a drawing at a lower level, it also appears in the higher level

![sdds](https://github.com/dev7355608/limits/assets/27728221/37d53bae-26e1-448c-9a41-389ced463599)

My intention was to create a dungeon with no light, but that doesn't seem to work.
![dsdssd](https://github.com/dev7355608/limits/assets/27728221/8b517cfe-95ac-4f5d-b16f-3dadb3d5af21)

Something wrong with my settings maybe?

**Comment by dev7355608** [comment]
1.1.0 is now compatibility with Levels.

https://github.com/dev7355608/limits/releases/tag/v1.1.0
