### ISSUE TITLE
[Feature Request] Add Limits Configuration to Items

### ISSUE THREAD

**Issue by maxobremer** [dev7355608/limits#13]
It would be nice if there was a button on the sheet of an item that has a template to configure the template of said item.

So lets say someone casts darkness, it would be nice if you on the item card of the spell could have already set up the limits of any measurement templates from that spell/item.

Having it look something like this?:
![image](https://github.com/dev7355608/limits/assets/86924581/6285f1fc-45b6-4797-b7eb-e9d6e05915bb)

**Comment by dev7355608** [comment]
Closing this. If the system or a module allows to attach Region Behavior to items, this will be possible. But I won't add this feature to Limits, because this feature could be it's own standalone module.
