### ISSUE TITLE
[Feature Request] Compatibility with PF2e module sight modes

### ISSUE THREAD

**Issue by Lule-NZ** [dev7355608/limits#14]
A request for your consideration if you have the time and inclination please.  Compatibility with the PF2e (Pathfinder second edition) system.  Especially Darkvsion and Greater Darkvision

**Comment by Lule-NZ** [comment]
In case this used to work or is supposed to already work, here is some version info:

Foundry: 11.313
PF2e: 5.7.4
Limits: 1.0.2

**Comment by dev7355608** [comment]
Limits can only limit detection modes that are defined. The PF2e system doesn't add detection modes for Darkvision or Greater Darkvision. If it did, you would be able limit these senses with Limits. So currently you can only limit normal eyesight and darkvision at the same time by limiting Basic Sight.
