### ISSUE TITLE
Add elevation and compatibility to Elevated Vision

### ISSUE THREAD

**Issue by rapus95** [dev7355608/limits#15]
would it be possible to make it compatible with the directed lights (which are there to emulate sun, moon and generic light on arbitrary height etc) of [Elevated Vision](https://github.com/caewok/fvtt-elevated-vision)?

That way I can disable global illumination to circumvent #3 and with elevation fields on limits' drawings, it'd be possible to properly calculate penetration reach of light and vision into limits' areas that come at an angle.

**Comment by rapus95** [comment]
Or wait for v12, x-ref https://github.com/dev7355608/limits/issues/16#issuecomment-1817959597

**Comment by dev7355608** [comment]
Closing this because Elevated Vision isn't V12 compatible (yet). Probably best to re-evaluate the compatibility once Elevated Vision  is V12 compatible.
