### ISSUE TITLE
add an option to restrict all visions based on ordinary sight at once for "heavily obscured areas"

### ISSUE THREAD

**Issue by rapus95** [dev7355608/limits#17]
Could either be solved by adding a "sense" "heavily obscured" which behaves like all visual sight based senses, or by introducing a toggle specific for heavily obscured.

**Comment by dev7355608** [comment]
I assume you want to be able quickly configure a limiting region and not input the same configuration again and again, right? I think user-configurable presets would be the solution here.

**Comment by rapus95** [comment]
Yes exactly! Presets would be awesome! Could think about also delivering predefined ones for 5e. But custom ones would be enough for sure. People will share their configurations then anyway :D

**Comment by dev7355608** [comment]
If there's a module out there that allows presets for Region Behaviors, this will be possible (maybe Mass Edit (?)). But I won't add it to Limits, because this feature could be a standalone module.
