### ISSUE TITLE
Templates with vision limits are visible in other scenes

### ISSUE THREAD

**Issue by KytesVI** [dev7355608/limits#2]
Tested with the following environment

- Foundry V11 306

Active Modules:
- Vision 5e v1.7.0
- Limits v0.1.0
- LibWrapper v1.12.13.0

Behaviour:

When switching scenes with a template or drawing using Limits, the vision limits also show on the new scene

Original scene:
![image](https://github.com/dev7355608/limits/assets/61651565/6a8ca673-4568-446e-9dfd-b15129835500)

New Scene
![image](https://github.com/dev7355608/limits/assets/61651565/a5813a43-af57-4148-bbbe-18db54d893d1)

Another example
![image](https://github.com/dev7355608/limits/assets/61651565/d5a3d479-d3fb-4e50-b869-be351f055ed0)

**Comment by Tarbarian** [comment]
This appears to be the case for all vision limiting objects, and makes using them pretty annoying as you can't have them exist in one scene without affecting all the other ones.

**Comment by dev7355608** [comment]
Thanks for the report! Fixed.

https://github.com/dev7355608/limits/releases/tag/v1.0.0
