### ISSUE TITLE
v12 compatiblity?

### ISSUE THREAD

**Issue by ctbritt** [dev7355608/limits#20]
Are there plans to update to v12 compatibility?

**Comment by dev7355608** [comment]
Yes. It's mostly done. Hopefully I find the time and energy to finish the v12 update soon.

**Comment by ctbritt** [comment]
Awesome! Sent from my iPadOn Jun 9, 2024, at 6:22 PM, dev7355608 ***@***.***> wrote:﻿
Yes. It's mostly done. Hopefully I find the time and energy to finish the v12 update soon.

**Comment by YenBenGrey** [comment]
Just adding an upvote or support for this, love this module.

**Comment by YenBenGrey** [comment]
I have just read something slightly worrying regarding limits on Discord Foundry.

Someone has said that in v12 limits may not relate to templates anymore. I only really use limits for templates very little else, maybe a couple of scenes where vision is magically reduced. 

Is this true? About the templates?

**Comment by SetArk** [comment]
> Yes. It's mostly done. Hopefully I find the time and energy to finish the v12 update soon.

YEEEEEEEEES! 
I was coming here to ask about plans to update to V12! 

UPVOTE for V12! 

Srsly Limits is one of my favorite modules for certain situations.

Thx for the work!

**Comment by dev7355608** [comment]
> Someone has said that in v12 limits may not relate to templates anymore.

@YenBenGrey That is correct. The only way to limit will be with regions going forward.

**Comment by YenBenGrey** [comment]
> > Someone has said that in v12 limits may not relate to templates anymore.
> 
> @YenBenGrey That is correct. The only way to limit will be with regions going forward.

Hello there,

Thank you for the reply. Please can I ask why?

It’s the only thing I use limits for.

**Comment by YenBenGrey** [comment]
Unless you’ll be able to use limits in regions then add the region to a template? 🤣

**Comment by dev7355608** [comment]
> > > Someone has said that in v12 limits may not relate to templates anymore.
> > 
> > 
> > @YenBenGrey That is correct. The only way to limit will be with regions going forward.
> 
> So, basically we would have to create a Region that is the whole map, or part of the map, and configure the new Limits through there?

That is correct. There will be something like a "Limit Range" behavior that you can add to your regions.

---

> > > Someone has said that in v12 limits may not relate to templates anymore.
> > 
> > 
> > @YenBenGrey That is correct. The only way to limit will be with regions going forward.
> 
> Hello there,
> 
> Thank you for the reply. Please can I ask why?
> 
> It’s the only thing I use limits for.

There are multiple reasons:
- I imagine either regions attached to templates or creating regions from templates will become common in the future, which would make direct support for templates unnecessary. There's already [this](https://foundryvtt.com/packages/region-attacher) module (I'm not sure how well it works/is implemented: I haven't tested it).
- I imagine  darkness light sources will be used for magical darkness now instead of Limits, which means a common use case for which Limits not supporting templates wouldn't be missed.
- I can delete a lot of code: a lot less for me to maintain.
- No more config injects and custom UI.
- I don't have to deal with flags anymore.

**Comment by YenBenGrey** [comment]
> * I imagine either regions attached to templates or creating regions from templates will become common in the future, which would make direct support for templates unnecessary. There's already [this](https://foundryvtt.com/packages/region-attacher) module (I'm not sure how well it works/is implemented: I haven't tested it).

I have tested it, the module above and it works VERY well and will compliment Limits perfectly.

**Comment by DoughyInTheMiddle** [comment]
This is literally the last post-12 addon that my campaign depends on. 

Yes, the tokens might have 60' of darkvision or more, but the module I'm running has a THICK fog in it (think of the movie The Mist) that limits their token vision to no more than 40'. 

I'm running this along with theripper93's 3D canvas and it works SO beautifully there as well, but I can find no other way to add this limitation back in.

The campaign kicks back up next week on 7/10. How far out we looking for the new version to go live for v12?

**Comment by SetArk** [comment]
> This is literally the last post-12 addon that my campaign depends on.
> 
> Yes, the tokens might have 60' of darkvision or more, but the module I'm running has a THICK fog in it (think of the movie The Mist) that limits their token vision to no more than 40'.
> 
> I'm running this along with theripper93's 3D canvas and it works SO beautifully there as well, but I can find no other way to add this limitation back in.
> 
> The campaign kicks back up next week on 7/10. How far out we looking for the new version to go live for v12?

PRETTY MUCH THE SAME SITUATION AS ME! 
Right now, i have 2 campaings that are literally in the middle of heavy fog. 
And both were stopped for an hiatus at the same time, and both on clifhanger moments for big encounters 

AND the idiot here, is preparing another campaign inspired in Fear and Hunger1\2 and one component will be some scenes with heavy fog, and others with pure darkness (Darkness can be navigated with torches of course, doesn't need the mod)

So yeah, 3 out 4 of my campaings are waiting for this mod to be able to come back without me having to manually change every token everytime they move into a Heavy Fog Scene xD

**Comment by DoughyInTheMiddle** [comment]
> So yeah, 3 out 4 of my campaings are waiting for this mod to be able to come back without me having to manually change every token everytime they move into a Heavy Fog Scene xD

Yeah, as I started reading your post, before I even got to this line, I *guess* I could just manually change everyone's vision ranges to 40.

**Comment by DoughyInTheMiddle** [comment]
> Yes. It's mostly done. Hopefully I find the time and energy to finish the v12 update soon.

Any progress update?

**Comment by Cempres** [comment]
excited for this! one of the last modules that i'm waiting upon before updating to v12

**Comment by YenBenGrey** [comment]
Hello there, 

I don't suppose this is going to be updated any time soon?

It was almost done on 9 June. My last gasp ask before I give up. lol

It was such a fantastic feature. :-)

**Comment by HongBo-contact** [comment]
Hi, I'm mostly writing this from probably a very different viewpoint than majority of the people in the thread, but for me the ability to add Limits to tiles and drawings was actually the main draw of the module. Is there a possibility that these functions would stay, maybe as a paid addon or something similar?

**Comment by YenBenGrey** [comment]
Hello there, 

I see the DEV is actively updating Vision5e which tells me that the DEV is active. 

Please can I ask if there can be any kind of update here at all, even if it is just to say that it won't be getting updated to v12 or the DEV is way too busy and to not expect anything soon?

I know it isn't paid for, this module, however I would pay for something like this compared to some stuff I pay for. 

I am actively diverting my players in a campaign from certain places because I am waiting for this module, it was that good. 

Please help?

**Comment by Rieler** [comment]
Just got foundry (started with v12) and this module seems to be the thing I sorely need for my campaign with a lot of underwater combat! I hope it updates soon💕

**Comment by dev7355608** [comment]
I've been hard at work. Potentially Limits 2.0.0 this weekend (no promises). Sneak peek:

![image](https://github.com/user-attachments/assets/11290c10-90b9-4665-99a7-d51db295d657)

**Comment by dev7355608** [comment]
Done: https://github.com/dev7355608/limits/releases/tag/v2.0.0
