### ISSUE TITLE
Bug: Vision5e overrides Limits

### ISSUE THREAD

**Issue by rayd99** [dev7355608/limits#21]
Foundry 11 build 315
D&D 3.1.2

Vision 5e: 1.14.3
Limits: 1.1.0

On a token, Darkvision is set as a racial sense to 60 feet as a trait of the Wood Elf race.
On the scene the token exists on, Darkvision is limited to 20 feet via the Limits feature.

The token has "Darkvision" (black/white) to 20 feet. It continues to have vision beyond that field to 60 feet.
Vision Range is set to 60 feet and not modifiable with a message "Automatically managed based on the Vision Mode and Detection Modes."
If I open the token and override the Darkvision value to 20 feet on the token, token's vision behaves as expected.

**Comment by dev7355608** [comment]
If it's a bug, it won't be fixed for Limits 1.x.x (V11). If this will still be an issue in Limits 2.0.0, feel free to reopen this issue.
