### ISSUE TITLE
Vision Distance Override

### ISSUE THREAD

**Issue by Yonman17** [dev7355608/limits#22]
I would like to suggest a basic vision distance limit that would shorten all vision distances.  This would allow certain actors to have vision restrictions and others would not

**Comment by dev7355608** [comment]
The UI in Limits 2.0.0 will be different and less inconvenient if you want to set the same limit for all detection modes, if that was your complaint. You'll just have to select all detection modes, but not set the range for each of them.

I do not intend to add a limit to the token config that affects only a specific token, if that is what you're suggesting in the second sentence.
