### ISSUE TITLE
The size of the window when making edits.

### ISSUE THREAD

**Issue by YenBenGrey** [dev7355608/limits#23]
Hello, 

Firstly just want to say that this module moving to v12 is the BEST news EVER!!

Anyway, when you open the dialogue window it fills the entire screen from top to bottom and you can't or I can't scroll down to the save button.
For now I am tabbing down to it. So maybe a feature request? Unless it is a Foundry issue with Region settings windows? 

If it is I will go there instead. 

Once again thank you for this.

**Comment by dev7355608** [comment]
Is your display resolution not very high? In theory the region behavior config should become scrollable if there's not enough vertical space. The region behavior config is automatically generated from the behavior data model by Foundry.

**Comment by YenBenGrey** [comment]
It was 1920x1080 on a 27 inch screen, just changed it up a gear and I can get the whole window in now but everything is tiny on my screen and my eyesight is not great. ha ha. Will have to stick with the tabbing method. Thank you anyways.

**Comment by dev7355608** [comment]
I made the config scrollable: https://github.com/dev7355608/limits/releases/tag/v2.0.1
