### ISSUE TITLE
Incompatible with Elevated Vision's Full Shadow Penumbra 

### ISSUE THREAD

**Issue by ButtFace1212** [dev7355608/limits#4]
![image](https://github.com/dev7355608/limits/assets/55815285/19547c5d-66f5-4d30-8054-f6a4ab2af0d9)
![image](https://github.com/dev7355608/limits/assets/55815285/eb695186-f04f-4066-8366-af898d9ab1f3)
![image](https://github.com/dev7355608/limits/assets/55815285/1ca15f5b-56d2-4a2f-ae09-49c20035fd7f)

Been trying to replicate magical darkness to block darkvision, light, and normal sight similar to the modules Vision Restrictions or Adequate Vision from past Foundry versions. It doesn't seem to be working at this moment. Foundry V11 2.2.2 Build 307; D&D 5th Edition 2.2.2. Images should be attached.

**Comment by dev7355608** [comment]
Are there error messages in the console (F12 -> Console tab)?

**Comment by dev7355608** [comment]
And you are on the latest version (1.0.0), right?

**Comment by ButtFace1212** [comment]
No error messages I can see about Vision 5e or Limits. I updated to 1.0.0 yeah; i was testing it a day or two ago and saw an update today so decided to try it again.

**Comment by dev7355608** [comment]
Is the template hidden perhaps?

If not. Could you try it with only Limits, libWrapper, and Vision 5e enabled.

**Comment by ButtFace1212** [comment]
The template is not hidden. I also tested it with only those three modules and it does work, so would that mean the issue is caused by another module? IIRC Find the Culprit! isn't v11 compatible so I'd have to go through all the modules manually; no problem with that, but will take a while with how many modules i have active.

**Comment by dev7355608** [comment]
Yeah, it could be a conflict with another module. It's very unfortunate that Find the Culprit isn't V11 compatible.

**Comment by dev7355608** [comment]
If you use Levels or Alternative Token Visibility, start with those. I can't think of any other module that could cause problems. If it's just templates that are not working, then maybe it could be a module that manipulates templates.

**Comment by ButtFace1212** [comment]
Okay it seems like Find the Culprit wanted to work today! I narrowed it down to the module "Elevated Vision" with specifically the lights not getting limited with the game setting "Full Shadow Penumbra" option, but everything else i'm not sure. Not sure if you'd want to see the issues with this module and Elevated Vision or not.

**Comment by dev7355608** [comment]
I'll look into it. Probably something needs to be done on Elevation Vision's end, but not sure.

**Comment by dev7355608** [comment]
Fixed in EV 0.5.8.
