### ISSUE TITLE
[Request] Common examples in readme

### ISSUE THREAD

**Issue by txm3278** [dev7355608/limits#5]
Can some common examples be added to the readme? Right now setting these up is a little confusing at first and takes a good amount of playing around with the options. An example would be 5e darkness.

**Comment by YenBenGrey** [comment]
Not to sound too desperate but I could really do with that Darkness macro template for tomorrow night. :-) lol

If I can help in any other way please let me know, I am good at testing stuff!

**Comment by dev7355608** [comment]
I added template macros for the Darkness, Fog Cloud, and Silence spell (D&D 5e) to the readme: https://github.com/dev7355608/limits#macros

**Comment by txm3278** [comment]
Thanks! Just curious on why you block movement with these?
