### ISSUE TITLE
override priority

### ISSUE THREAD

**Issue by amir-arad** [dev7355608/limits#8]
Hi

First of all, thank you for this awesome module.

I'm trying to migrate from Perfect Vision, and I have a scene with overlapping shapes that have different sight limits. 
My goal is to create an area of limited vision (jungle), with some pockets of better visions inside it (clearings). example:
![image](https://github.com/dev7355608/limits/assets/6019373/55b66802-3cda-45e7-817e-5e6030a5a392)

It seems that I the actual limit is always the more strict of the overlapping shapes. In Perfect Vision, I used to be able to set the priority between the shapes by changing their z-index, so that the one on top will set the sight limits.

I would greatly appreciate this kind of capability in Limits.

**Comment by dev7355608** [comment]
I'll likely won't support this until V12 when Scene Regions are added: they should allow defining limits in regions with holes easily without the need for multiple shapes with different z-indices that override each other.

Until then I recommend to split it into multiple regions like this for example: 
![image](https://github.com/dev7355608/limits/assets/31905376/5a40dee2-ef59-42a0-a2e3-1351127facb2)

**Comment by amir-arad** [comment]
ok, thanks for the tip.
