### ISSUE TITLE
[BUG?] Hiding a drawing does turn "limits" settings off.

### ISSUE THREAD

**Issue by Berytak** [dev7355608/limits#9]
When I hide a drawing where I configured some vision restrictions, the settings have no effect. The restrictions just work while the drawing is not hidden.
This is kind of a bummer, because I don't want to break the immersion of a map with several lines of drawings. It would be great if the restrictions/settings would effect player tokens even it the drawing is hidden. 
I tested this only with drawings, because I need complex shapes (forest with thick undergrowth for example).

Thanks in advance!

Cheers
Berytak

**Comment by dev7355608** [comment]
Working as intended. Hidden things shouldn't really affect anything in the scene. Imagine you want place a drawing/template for a vision limiting effect like smoke that is activated by a trap: it's hidden until the trap is activated.

I added the *Invisible* option to the *Advanced Drawing Tools* module: https://github.com/dev7355608/advanced-drawing-tools/releases/tag/v2.1.0

In V12 we'll hopefully be able to ditch drawings in favor of Scene Regions to define limited areas in more powerful way with better UI/UX.

**Comment by Berytak** [comment]
Personally, I would have preferred a separate button in the context menu of the drawing to hide the limitation, but of course I understand the decision. Nevertheless, it is still a pity.
